image: "ruby:2.5"
before_script:
  - apt-get update -qy
  - apt-get -y install zip unzip

stages:
  - build

build:
  stage: build
  script:
    - zip mountup.zip -r mountup -x ".*"
  artifacts:
    name: mountup
    when: on_success
    paths:
      - mountup.zip
  when: on_success
  only:
    - tags
